[platformio]
default_envs = esp32dev
src_dir = .

[common]
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  majicdesigns/MD_Parola
  majicdesigns/MD_MAX72XX
  ESP32Async/ESPAsyncWebServer @ ^3.9.1

[env]
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}

[env:esp8266_d1_mini]
platform = espressif8266
board = d1_mini
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
build_src_filter =
  +<ESPTimeCast_ESP8266/>
  -<ESPTimeCast_ESP32/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=14
  -DESPTIMECAST_DEFAULT_CS=13
  -DESPTIMECAST_DEFAULT_DATA=15
lib_deps =
  ${common.lib_deps}
  ESP32Async/ESPAsyncTCP

[env:esp8266_esp12f]
platform = espressif8266
board = esp12e
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
build_src_filter =
  +<ESPTimeCast_ESP8266/>
  -<ESPTimeCast_ESP32/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=14
  -DESPTIMECAST_DEFAULT_CS=13
  -DESPTIMECAST_DEFAULT_DATA=12
lib_deps =
  ${common.lib_deps}
  ESP32Async/ESPAsyncTCP

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=18
  -DESPTIMECAST_DEFAULT_CS=23
  -DESPTIMECAST_DEFAULT_DATA=5
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_s2_mini]
platform = espressif32
board = lolin_s2_mini
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=7
  -DESPTIMECAST_DEFAULT_CS=11
  -DESPTIMECAST_DEFAULT_DATA=12
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_s2_feather]
platform = espressif32
board = adafruit_feather_esp32s2
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=36
  -DESPTIMECAST_DEFAULT_CS=10
  -DESPTIMECAST_DEFAULT_DATA=35
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=4
  -DESPTIMECAST_DEFAULT_CS=10
  -DESPTIMECAST_DEFAULT_DATA=6
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_s3_wroom]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=18
  -DESPTIMECAST_DEFAULT_CS=16
  -DESPTIMECAST_DEFAULT_DATA=17
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_s3_supermini]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=4
  -DESPTIMECAST_DEFAULT_CS=5
  -DESPTIMECAST_DEFAULT_DATA=6
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP

[env:esp32_s3_zero]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<ESPTimeCast_ESP32/>
  -<ESPTimeCast_ESP8266/>
build_flags =
  -DESPTIMECAST_DEFAULT_CLK=12
  -DESPTIMECAST_DEFAULT_CS=11
  -DESPTIMECAST_DEFAULT_DATA=10
lib_deps =
  ${common.lib_deps}
  ESP32Async/AsyncTCP
